### ISSUE TITLE
VM becomes unresponsive to bosh after reboot

### ISSUE THREAD

**Issue by gossion** [cloudfoundry-incubator/bosh-windows-stemcell-builder#35]
Not sure if you realize this issue.

I tried a test to deploy a simple workload on Windows VM on Azure,  it deployed successfully. The problem is that when I tried to restart the VM (via azure portal), the VMs became unresponsive forever and never came back to service.

```
guwe@guwecf0628:~/workspace/sample-go-windows-boshrelease$ bosh -e azure vms
Using environment '10.0.0.4' as client 'admin'

Task 967. Done

Deployment 'webapp'

Instance                                      Process State       AZ  IPs  VM CID
                   VM Type  Active
webapp1/56d68506-4ed6-4e0c-a9bf-fa9624a29b09  unresponsive agent  z2  -    agent_id:f95268c3-a067-4b09-ba9f-65c0ae2d2fe8;resource_gr
oup_name:guwe0628  small    true
webapp1/8452e005-bb6e-49ff-b7dc-0b74b492db0e  unresponsive agent  z1  -    agent_id:066b3e8d-6c9e-4c8e-84a3-fcf4b3b262a8;resource_gr
oup_name:guwe0628  small    true

2 vms

Succeeded

```

My env: 
* cloud provider: Azure

* stemcell: 
https://bosh.io/stemcells/bosh-azure-hyperv-windows1803-go_agent

* manifest:
```yaml
---
name: webapp

instance_groups:
- name: webapp1
  azs: [z1, z2, z3]
  instances: 2
  vm_type: small
  stemcell: windows1803
  networks:
    - name: default
      default: [gateway, dns]
    #- name: network2
  jobs:
  - name: simple-go-web-app
    release: sample-go-windows
    properties:
      port: 3000


variables: []

stemcells:
- alias: windows
  os: windows2012R2
  version: latest
- alias: "windows1803"
  os: "windows1803"
  version: "1803.2"

update:
  canaries: 1
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000
  max_in_flight: 1
  serial: false

releases:
- name: sample-go-windows
  version: 1.0.0
  url: https://github.com/cloudfoundry-community/sample-go-windows-boshrelease/releases/download/v1.0.0/sample-go-windows-1.0.0.tgz
  sha1: 7d15b2bd43acf849fac5f6ec805e0b6cfa1b9bb5
```

I believe the VM was up because it had response to RDP. Maybe there is an issue with bosh-agent, however, I don't have a credential to login to VM to check.
